// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.17.2
// source: score-engine-service.proto

package score

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type TennisMatchTuple struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TournamentID int64              `protobuf:"varint,2,opt,name=tournamentID,proto3" json:"tournamentID,omitempty"`
	StartsAt     int64              `protobuf:"varint,3,opt,name=startsAt,proto3" json:"startsAt,omitempty"`
	Player1      *TennisPlayerTuple `protobuf:"bytes,4,opt,name=player1,proto3" json:"player1,omitempty"`
	Player2      *TennisPlayerTuple `protobuf:"bytes,5,opt,name=player2,proto3" json:"player2,omitempty"`
	Winner       string             `protobuf:"bytes,6,opt,name=winner,proto3" json:"winner,omitempty"`
}

func (x *TennisMatchTuple) Reset() {
	*x = TennisMatchTuple{}
	if protoimpl.UnsafeEnabled {
		mi := &file_score_engine_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TennisMatchTuple) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TennisMatchTuple) ProtoMessage() {}

func (x *TennisMatchTuple) ProtoReflect() protoreflect.Message {
	mi := &file_score_engine_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TennisMatchTuple.ProtoReflect.Descriptor instead.
func (*TennisMatchTuple) Descriptor() ([]byte, []int) {
	return file_score_engine_service_proto_rawDescGZIP(), []int{0}
}

func (x *TennisMatchTuple) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TennisMatchTuple) GetTournamentID() int64 {
	if x != nil {
		return x.TournamentID
	}
	return 0
}

func (x *TennisMatchTuple) GetStartsAt() int64 {
	if x != nil {
		return x.StartsAt
	}
	return 0
}

func (x *TennisMatchTuple) GetPlayer1() *TennisPlayerTuple {
	if x != nil {
		return x.Player1
	}
	return nil
}

func (x *TennisMatchTuple) GetPlayer2() *TennisPlayerTuple {
	if x != nil {
		return x.Player2
	}
	return nil
}

func (x *TennisMatchTuple) GetWinner() string {
	if x != nil {
		return x.Winner
	}
	return ""
}

type TennisPlayerTuple struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	First string `protobuf:"bytes,2,opt,name=first,proto3" json:"first,omitempty"`
	Last  string `protobuf:"bytes,3,opt,name=last,proto3" json:"last,omitempty"`
}

func (x *TennisPlayerTuple) Reset() {
	*x = TennisPlayerTuple{}
	if protoimpl.UnsafeEnabled {
		mi := &file_score_engine_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TennisPlayerTuple) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TennisPlayerTuple) ProtoMessage() {}

func (x *TennisPlayerTuple) ProtoReflect() protoreflect.Message {
	mi := &file_score_engine_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TennisPlayerTuple.ProtoReflect.Descriptor instead.
func (*TennisPlayerTuple) Descriptor() ([]byte, []int) {
	return file_score_engine_service_proto_rawDescGZIP(), []int{1}
}

func (x *TennisPlayerTuple) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TennisPlayerTuple) GetFirst() string {
	if x != nil {
		return x.First
	}
	return ""
}

func (x *TennisPlayerTuple) GetLast() string {
	if x != nil {
		return x.Last
	}
	return ""
}

type TennisMatchesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TournamentID int64  `protobuf:"varint,1,opt,name=tournamentID,proto3" json:"tournamentID,omitempty"`
	Category     string `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Round        string `protobuf:"bytes,3,opt,name=round,proto3" json:"round,omitempty"`
}

func (x *TennisMatchesRequest) Reset() {
	*x = TennisMatchesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_score_engine_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TennisMatchesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TennisMatchesRequest) ProtoMessage() {}

func (x *TennisMatchesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_score_engine_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TennisMatchesRequest.ProtoReflect.Descriptor instead.
func (*TennisMatchesRequest) Descriptor() ([]byte, []int) {
	return file_score_engine_service_proto_rawDescGZIP(), []int{2}
}

func (x *TennisMatchesRequest) GetTournamentID() int64 {
	if x != nil {
		return x.TournamentID
	}
	return 0
}

func (x *TennisMatchesRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *TennisMatchesRequest) GetRound() string {
	if x != nil {
		return x.Round
	}
	return ""
}

type TennisMatchesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Matches []*TennisMatchTuple `protobuf:"bytes,1,rep,name=matches,proto3" json:"matches,omitempty"`
}

func (x *TennisMatchesResponse) Reset() {
	*x = TennisMatchesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_score_engine_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TennisMatchesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TennisMatchesResponse) ProtoMessage() {}

func (x *TennisMatchesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_score_engine_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TennisMatchesResponse.ProtoReflect.Descriptor instead.
func (*TennisMatchesResponse) Descriptor() ([]byte, []int) {
	return file_score_engine_service_proto_rawDescGZIP(), []int{3}
}

func (x *TennisMatchesResponse) GetMatches() []*TennisMatchTuple {
	if x != nil {
		return x.Matches
	}
	return nil
}

var File_score_engine_service_proto protoreflect.FileDescriptor

var file_score_engine_service_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x2d, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2d, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x61,
	0x69, 0x6e, 0x22, 0xe0, 0x01, 0x0a, 0x10, 0x54, 0x65, 0x6e, 0x6e, 0x69, 0x73, 0x4d, 0x61, 0x74,
	0x63, 0x68, 0x54, 0x75, 0x70, 0x6c, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x74, 0x6f, 0x75, 0x72, 0x6e,
	0x61, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x74,
	0x6f, 0x75, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x73, 0x41, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x73, 0x41, 0x74, 0x12, 0x31, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x31, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e,
	0x54, 0x65, 0x6e, 0x6e, 0x69, 0x73, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x54, 0x75, 0x70, 0x6c,
	0x65, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x31, 0x12, 0x31, 0x0a, 0x07, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x32, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6d, 0x61,
	0x69, 0x6e, 0x2e, 0x54, 0x65, 0x6e, 0x6e, 0x69, 0x73, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x54,
	0x75, 0x70, 0x6c, 0x65, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x32, 0x12, 0x16, 0x0a,
	0x06, 0x77, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x77,
	0x69, 0x6e, 0x6e, 0x65, 0x72, 0x22, 0x4d, 0x0a, 0x11, 0x54, 0x65, 0x6e, 0x6e, 0x69, 0x73, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x54, 0x75, 0x70, 0x6c, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x69,
	0x72, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x66, 0x69, 0x72, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x6c, 0x61, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6c, 0x61, 0x73, 0x74, 0x22, 0x6c, 0x0a, 0x14, 0x54, 0x65, 0x6e, 0x6e, 0x69, 0x73, 0x4d, 0x61,
	0x74, 0x63, 0x68, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0c,
	0x74, 0x6f, 0x75, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0c, 0x74, 0x6f, 0x75, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x44,
	0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x72, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x6f, 0x75,
	0x6e, 0x64, 0x22, 0x49, 0x0a, 0x15, 0x54, 0x65, 0x6e, 0x6e, 0x69, 0x73, 0x4d, 0x61, 0x74, 0x63,
	0x68, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x07, 0x6d,
	0x61, 0x74, 0x63, 0x68, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6d,
	0x61, 0x69, 0x6e, 0x2e, 0x54, 0x65, 0x6e, 0x6e, 0x69, 0x73, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x54,
	0x75, 0x70, 0x6c, 0x65, 0x52, 0x07, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x73, 0x32, 0x5a, 0x0a,
	0x0c, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4a, 0x0a,
	0x0d, 0x54, 0x65, 0x6e, 0x6e, 0x69, 0x73, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x73, 0x12, 0x1a,
	0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x54, 0x65, 0x6e, 0x6e, 0x69, 0x73, 0x4d, 0x61, 0x74, 0x63,
	0x68, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x6d, 0x61, 0x69,
	0x6e, 0x2e, 0x54, 0x65, 0x6e, 0x6e, 0x69, 0x73, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x3b,
	0x6d, 0x61, 0x69, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_score_engine_service_proto_rawDescOnce sync.Once
	file_score_engine_service_proto_rawDescData = file_score_engine_service_proto_rawDesc
)

func file_score_engine_service_proto_rawDescGZIP() []byte {
	file_score_engine_service_proto_rawDescOnce.Do(func() {
		file_score_engine_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_score_engine_service_proto_rawDescData)
	})
	return file_score_engine_service_proto_rawDescData
}

var file_score_engine_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_score_engine_service_proto_goTypes = []interface{}{
	(*TennisMatchTuple)(nil),      // 0: main.TennisMatchTuple
	(*TennisPlayerTuple)(nil),     // 1: main.TennisPlayerTuple
	(*TennisMatchesRequest)(nil),  // 2: main.TennisMatchesRequest
	(*TennisMatchesResponse)(nil), // 3: main.TennisMatchesResponse
}
var file_score_engine_service_proto_depIdxs = []int32{
	1, // 0: main.TennisMatchTuple.player1:type_name -> main.TennisPlayerTuple
	1, // 1: main.TennisMatchTuple.player2:type_name -> main.TennisPlayerTuple
	0, // 2: main.TennisMatchesResponse.matches:type_name -> main.TennisMatchTuple
	2, // 3: main.ScoreService.TennisMatches:input_type -> main.TennisMatchesRequest
	3, // 4: main.ScoreService.TennisMatches:output_type -> main.TennisMatchesResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_score_engine_service_proto_init() }
func file_score_engine_service_proto_init() {
	if File_score_engine_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_score_engine_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TennisMatchTuple); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_score_engine_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TennisPlayerTuple); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_score_engine_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TennisMatchesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_score_engine_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TennisMatchesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_score_engine_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_score_engine_service_proto_goTypes,
		DependencyIndexes: file_score_engine_service_proto_depIdxs,
		MessageInfos:      file_score_engine_service_proto_msgTypes,
	}.Build()
	File_score_engine_service_proto = out.File
	file_score_engine_service_proto_rawDesc = nil
	file_score_engine_service_proto_goTypes = nil
	file_score_engine_service_proto_depIdxs = nil
}
